version: '3'
services:
  test-mongo:
     image: mongo
     container_name: mongo-docker
     command: --smallfiles
  track-service:
#      image:
#          docker-spring
     build: track-service/
     restart: always
     container_name: track-service
     links:
       - test-mongo
       - config-server
       - eureka-server
       - api-server
     depends_on:
       - test-mongo
       - config-server
       - api-server
#     ports:
#          - 8092:8092
  config-server:
#      image:
#          docker-configuration
     build: config-server/
     restart: always
     container_name: config-server
  eureka-server:
#      image:
#          docker-eureka
     build: eureka-server/
     restart: always
     container_name: eureka-server
#     ports:
#          - 9090:9090
  user-service:
    #      image:
    #          docker-spring
    build: user-service/
    restart: always
    container_name: user-service
    links:


      - eureka-server
      - api-server
    depends_on:

      - config-server
      - api-server
#    ports:
#      - 8092:8092
  api-server:
    build: api-server/
    restart: always
    container_name: api-server
    ports:
      - 8085:8085
